name = "drift_record"
version = "1.0.0"

description = "Record logs for drift steppers, and use them in snapshot tests."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "drift", path = "drift_js" }
internal_modules = ["drift/js/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
drift = { path = "../drift" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.3.0 and < 2.0.0"
exemplify = { path = "../dev/exemplify" }
