name = "drift_js"
version = "1.1.0"
target = "javascript"

description = "Run drift steppers on JavaScript targets."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "drift", path = "drift_js", tag-prefix = "drift_js-" }
internal_modules = ["drift/js/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
drift = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
checkmark = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
