name = "drift_actor"
version = "1.0.0"

description = "Run drift steppers as an OTP actor on Erlang."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "drift", path = "drift" }

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
drift = { path = "../drift" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
exemplify = { path = "../dev/exemplify" }
